In [64]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split,  cross_val_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn import preprocessing
from scipy.stats import norm, skew
from sklearn.preprocessing import StandardScaler #preprocessing by removing the mean and scaling to unit variance
from sklearn.linear_model import LinearRegression, RidgeCV, LassoCV, ElasticNetCV # Models 
from sklearn.metrics import mean_squared_error, make_scorer # Grading your models

import matplotlib.pyplot as plt # more visualization for your data
import seaborn as sns # Even more visualization, helps you understand your data
import datetime as dt
import numpy as np
import pandas as pd
import requests
import json
from pprint import pprint
import csv
# from api_key import api_key
from flask import Flask, jsonify, render_template

from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
import sqlalchemy

In [3]:
engine = create_engine('sqlite:///../data/china_trade.sqlite', echo=False)

In [5]:
Base = automap_base()
Base.prepare(engine, reflect=True)
session = Session(engine)

In [94]:
IndImports = Base.classes.hs2import
IndExports = Base.classes.hs2export
YRImports = Base.classes.yrhs2import
YRExports = Base.classes.yrhs2export
Imports = Base.classes.imports
Exports = Base.classes.export

In [129]:
stmt = session.query(Imports).statement
df = pd.read_sql_query(stmt, session.bind)

index  YTDValue  MoValue   Period  \
0      0  12238358  5385854  2015-02   
1      1  16629923  4391565  2015-03   
2      2  19522841  2892918  2015-04   
3      3  23971868  4449027  2015-05   
4      4  29755208  5783340  2015-06   

                                         Description  HSC  
0  FISH, DRIED, SALTED ETC, SMOKED ETC; ED FISH MEAL  305  
1  FISH, DRIED, SALTED ETC, SMOKED ETC; ED FISH MEAL  305  
2  FISH, DRIED, SALTED ETC, SMOKED ETC; ED FISH MEAL  305  
3  FISH, DRIED, SALTED ETC, SMOKED ETC; ED FISH MEAL  305  
4  FISH, DRIED, SALTED ETC, SMOKED ETC; ED FISH MEAL  305

In [138]:
df['Period'] = pd.to_datetime(df['Period'])

df.Period = pd.to_numeric(df.Period, errors='coerce')


In [139]:
y = df.YTDValue

In [163]:
features = ['MoValue', 'Period', 'HSC']
X = df[features]

In [165]:
train_X, val_X, train_y, val_y = train_test_split(X, y, test_size=0.2, 
                                                    random_state=123
                                                    )

In [166]:
imports_model = DecisionTreeRegressor(random_state=1)

In [167]:
imports_model.fit(train_X, train_y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf='deprecated',
           min_samples_split=2, min_weight_fraction_leaf='deprecated',
           presort=False, random_state=1, splitter='best')

In [150]:
val_predictions = imports_model.predict(val_X)

In [151]:
val_mae = mean_absolute_error(val_predictions, val_y)


In [179]:
imports_model = DecisionTreeRegressor(max_leaf_nodes=100, random_state=1)


In [180]:
imports_model.fit(train_X, train_y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=100, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf='deprecated',
           min_samples_split=2, min_weight_fraction_leaf='deprecated',
           presort=False, random_state=1, splitter='best')

In [154]:
print("Validation MAE for best value of max_leaf_nodes: {:,.0f}".format(val_mae))


Validation MAE for best value of max_leaf_nodes: 74,480,536


In [162]:
train_X_scaled = preprocessing.scale(train_X)
print(train_X_scaled)

[[-0.16715562 -0.92872901 -0.00457137]
 [ 0.03923614  1.05410697  1.1150328 ]
 [-0.16720446 -0.85658357 -1.79221225]
 ...
 [-0.16375279 -0.85658357 -0.00382621]
 [-0.12824895  1.4799978  -0.93714017]
 [-0.08076255 -1.28480167  1.37434878]]


C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64 were all converted to float64 by the scale function.
  """Entry point for launching an IPython kernel.
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\preprocessing\data.py:176: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


In [156]:
print(train_X_scaled.mean(axis=0))


[-7.62212736e-18  2.13419566e-17  3.43396896e-17]


In [168]:
imports_model.describe()

AttributeError: 'DecisionTreeRegressor' object has no attribute 'describe'

In [178]:
train

NameError: name 'train' is not defined

In [183]:
duty = pd.read_csv("~/Documents/Class/Applied_MFN_Tariffs.csv")

ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 3


In [184]:
df

index    YTDValue    MoValue               Period  \
0          0    12238358    5385854  1422748800000000000   
1          1    16629923    4391565  1425168000000000000   
2          2    19522841    2892918  1427846400000000000   
3          3    23971868    4449027  1430438400000000000   
4          4    29755208    5783340  1433116800000000000   
5          5    35828070    6072862  1435708800000000000   
6          6    40715428    4887358  1438387200000000000   
7          7    46719724    6004296  1441065600000000000   
8          8    51674573    4954849  1443657600000000000   
9          9    57521143    5846570  1446336000000000000   
10        10    62787036    5265893  1448928000000000000   
11        11     5995226    5995226  1451606400000000000   
12        12    12011644    6016418  1454284800000000000   
13        13    14496728    2485084  1456790400000000000   
14        14    17683566    3186838  1459468800000000000   
15        15    21363425    3679859  1462060800000000000   
16        16    25098751    3735326  1464739200000000000   
17        17    29254450    4155699  1467331200000000000   
18        18    34091277    4836827  1470009600000000000   
19        19    37074738    2983461  1472688000000000000   
20        20    41887059    4812321  1475280000000000000   
21        21    47419965    5532906  1477958400000000000   
22        22    53795905    6375940  1480550400000000000   
23        23     7283966    7283966  1483228800000000000   
24        24    14338683    7054717  1485907200000000000   
25        25    17735238    3396555  1488326400000000000   
26        26    22042017    4306779  1491004800000000000   
27        27    25051907    3009890  1493596800000000000   
28        28    29235727    4183820  1496275200000000000   
29        29    32587371    3351644  1498867200000000000   
...      ...         ...        ...                  ...   
55321  55321  2608565542  323084695  1535760000000000000   
55322  55322  2964667788  356102246  1538352000000000000   
55323  55323  3295502634  330834846  1541030400000000000   
55324  55324  3609020146  313517512  1543622400000000000   
55325  55325   325342727  325342727  1546300800000000000   
55326  55326      210016     210016  1483228800000000000   
55327  55327      803243     593227  1485907200000000000   
55328  55328     1344719     541476  1488326400000000000   
55329  55329     1983373     638654  1491004800000000000   
55330  55330     2808655     825282  1493596800000000000   
55331  55331     3491019     682364  1496275200000000000   
55332  55332     4057998     566979  1498867200000000000   
55333  55333     5134997    1076999  1501545600000000000   
55334  55334     6842752    1707755  1504224000000000000   
55335  55335     8505682    1662930  1506816000000000000   
55336  55336     9629081    1123399  1509494400000000000   
55337  55337    10560199     931118  1512086400000000000   
55338  55338     1367252    1367252  1514764800000000000   
55339  55339     3247207    1879955  1517443200000000000   
55340  55340     5005341    1758134  1519862400000000000   
55341  55341     6390809    1385468  1522540800000000000   
55342  55342     7855477    1464668  1525132800000000000   
55343  55343    10293792    2438315  1527811200000000000   
55344  55344    12002084    1708292  1530403200000000000   
55345  55345    13816547    1814463  1533081600000000000   
55346  55346    16225220    2408673  1535760000000000000   
55347  55347    18913317    2688097  1538352000000000000   
55348  55348    21687997    2774680  1541030400000000000   
55349  55349    25122310    3434313  1543622400000000000   
55350  55350     1849689    1849689  1546300800000000000   

                                             Description   HSC  
0      FISH, DRIED, SALTED ETC, SMOKED ETC; ED FISH MEAL   305  
1      FISH, DRIED, SALTED ETC, SMOKED ETC; ED FISH MEAL   305  
2      FISH, DRIED, SALTED ETC, SMOKED ETC; ED FISH MEAL   305  
3      FISH, DRIED, SALTED